---
title: "Activity: Exploring Data: Chicago Restaurant Inspections"
author: "Your Name Here!"
format: html
editor: visual
---

The city of Chicago partnered with Allstate Insurance to develop a data-driven model for prioritizing its health inspections. The goal of this model was to predict whether an inspector would observe a critical violation during the upcoming inspection.

In this activity, you are going to explore a subset of their data. You should approach this activity as a data scientist: as you go through each step, discuss with your group what variable you want to look at, how you are going to explore it, and what you have learned after making and interpreting appropriate tables, graphs, or subsets.

This activity is very open-ended! Please call me over if your group is stuck (either what to do next or how to code what you want to do).

```{r}
#| label: import packages and data

here::i_am("Activities/Exploring-Relationships-Chicago-Restaurants.qmd")

library(tidyverse)
library(lubridate) # possibly useful if you want to explore inspection_date

chicago <- readr::read_csv(here::here("Data/Chicago_inspections.csv"))
```

## Step 1: Understanding the Data

Answer the following questions about the `chicago` dataset you just imported. The accompanying data dictionary (on Canvas) may be useful.

1.  For which year(s) do you have inspection data?

2.  How many inspections are in the dataset?

3.  Which variables are numerical? Categorical? Logical? Date?

4.  The response variable of interest whether an inspector observed a critical violation during the (current) inspection. This variable is not in the dataset! Write code to create it.

## Step 2: Explore the Response Variable

1.  Are there any missing values of the response variable?

2.  Produce appropriate numerical and graphical summaries describing the distribution of the response variable.

3.  Write a brief (2-3 sentences) paragraph indicating what you have learned about the response variable, based on your exploration.

## Step 3: Identify and Explore a Useful Explanatory Variable

1.  Pick one explanatory variable in the dataset. Explain why you think it might be related to the response variable: what kind of relationship are you expecting and why?

2.  Are there any missing values of the variable? Produce appropriate numerical and graphical summaries describing the distribution of the variable.

3.  Are there any weird values of the variable (*truly unusual* outlier values or categories with only a few inspections)? If so, which `Inspection_ID` do they correspond to?

4.  Write a brief (2-3 sentences) paragraph indicating what you have learned about the explanatory variable, based on your exploration.

## Step 4: Describe the Relationship Between the Two Variables

1.  Produce a graph showing the relationship between the variables from Step 2 and Step 3.

2.  What do you notice about the relationship? If appropriate, consider adding a linear or nonlinear trend (or both) to the graph to help you.

## Step 5: Repeat Steps 3-4 for More Variables

1.  Pick another explanatory variable in the dataset or create a new explanatory variable (such as `inspection_month`) from the existing ones. Explain why you think the variable you chose/created might be related to the response variable: what kind of relationship are you expecting and why?

2.  Are there any missing values of the variable? Produce appropriate numerical and graphical summaries describing the distribution of the variable.

3.  Are there any weird values of the variable (*truly unusual* outlier values or categories with only a few inspections)? If so, which `Inspection_ID` do they correspond to?

4.  Produce a graph showing the relationship between the explanatory and response variables. Consider whether keeping the *truly unusual* values would be important for giving a fuller description of the relationship and/or whether removing them would make the summaries and graphs more interpretabel.

5.  What do you notice about the relationship? If appropriate, consider adding a linear or nonlinear trend (or both) to the graph to help you.

6.  Produce a graph showing the relationship between two explanatory variables you have looked at. What do you notice about the relationship? If appropriate, consider adding a linear or nonlinear trend (or both) to the graph to help you.

7.  If possible, produce tables and/or graphs showing the relationship between all three variables. If appropriate, consider adding a linear or nonlinear trend within each group to the graph to help you.

8.  Write a brief (2-3 sentences) paragraph indicating what you have learned by exploring this variable.
